function C1 = MGH(in1,in2,in3)
%MGH
%    C1 = MGH(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:18

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in2(1,:);
com12 = in2(2,:);
theta1 = in3(3,:);
x1 = in3(1,:);
y1 = in3(2,:);
t2 = cos(theta1);
t3 = H12-com12;
t4 = sin(theta1);
t5 = H11-com11;
C1 = [-H11+x1+t2.*t5-t3.*t4;-H12+y1+t2.*t3+t4.*t5];
