function C1_qq = MGH_qq(in1,in2,in3,in4)
%MGH_QQ
%    C1_QQ = MGH_QQ(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:19

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in2(1,:);
com12 = in2(2,:);
theta1 = in3(3,:);
thetad1 = in4(3,:);
t2 = thetad1.^2;
t3 = cos(theta1);
t4 = H12-com12;
t5 = sin(theta1);
t6 = H11-com11;
C1_qq = [-t2.*(t3.*t6-t4.*t5);-t2.*(t3.*t4+t5.*t6)];
