function C1_q = MGH_q(in1,in2,in3)
%MGH_Q
%    C1_Q = MGH_Q(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:19

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in2(1,:);
com12 = in2(2,:);
theta1 = in3(3,:);
t2 = cos(theta1);
t3 = H11-com11;
t4 = sin(theta1);
t5 = H12-com12;
C1_q = reshape([1.0,0.0,0.0,1.0,-t2.*t5-t3.*t4,t2.*t3-t4.*t5],[2,3]);
