function C3 = MGP(in1,alpha,in3,in4)
%MGP
%    C3 = MGP(IN1,ALPHA,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:21

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in3(1,:);
com12 = in3(2,:);
theta1 = in4(3,:);
x1 = in4(1,:);
y1 = in4(2,:);
t2 = cos(theta1);
t3 = H12-com12;
t4 = sin(theta1);
t5 = H11-com11;
C3 = -cos(alpha).*(-H12+y1+t2.*t3+t4.*t5)-sin(alpha).*(H11-x1-t2.*t5+t3.*t4);
