function C3_qq = MGP_qq(in1,alpha,in3,in4,in5)
%MGP_QQ
%    C3_QQ = MGP_QQ(IN1,ALPHA,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:21

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in3(1,:);
com12 = in3(2,:);
theta1 = in4(3,:);
thetad1 = in5(3,:);
t2 = cos(theta1);
t3 = H11-com11;
t4 = sin(theta1);
t5 = H12-com12;
C3_qq = thetad1.^2.*(cos(alpha).*(t2.*t5+t3.*t4)-sin(alpha).*(t2.*t3-t4.*t5));
