function C4_q = MGPm_q(in1,alpha,a,w,in5,t,in7)
%MGPM_Q
%    C4_Q = MGPM_Q(IN1,ALPHA,A,W,IN5,T,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:22

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in5(1,:);
com12 = in5(2,:);
theta1 = in7(3,:);
t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(theta1);
t5 = H12-com12;
t6 = sin(theta1);
t7 = H11-com11;
t8 = t4.*t7;
t9 = t4.*t5;
t10 = t6.*t7;
C4_q = reshape([t3,1.0,-t2,1.0,-t3.*(t9+t10)-t2.*(t8-t5.*t6),t8-t9-t10-t5.*t6],[2,3]);
