function C4_tt = MGPm_tt(in1,alpha,a,w,in5,t,in7)
%MGPM_TT
%    C4_TT = MGPM_TT(IN1,ALPHA,A,W,IN5,T,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:23

C4_tt = [0.0;a.*w.^2.*sin(t.*w)];
