function C4_qq = MGPm_qq(in1,alpha,a,w,in5,t,in7,in8)
%MGPM_QQ
%    C4_QQ = MGPM_QQ(IN1,ALPHA,A,W,IN5,T,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:22

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in5(1,:);
com12 = in5(2,:);
theta1 = in7(3,:);
thetad1 = in8(3,:);
t2 = cos(theta1);
t3 = H11-com11;
t4 = sin(theta1);
t5 = H12-com12;
t6 = thetad1.^2;
t7 = t2.*t3;
t8 = t2.*t5;
t9 = t3.*t4;
C4_qq = [-t6.*(sin(alpha).*(t7-t4.*t5)-cos(alpha).*(t8+t9));-t6.*(t7+t8+t9-t4.*t5)];
