function C4_t = MGPm_t(in1,alpha,a,w,in5,t,in7)
%MGPM_T
%    C4_T = MGPM_T(IN1,ALPHA,A,W,IN5,T,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:22

C4_t = [0.0;-a.*w.*cos(t.*w)];
