function C4_qt = MGPm_qt(in1,alpha,a,w,in5,t,in7,in8)
%MGPM_QT
%    C4_QT = MGPM_QT(IN1,ALPHA,A,W,IN5,T,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:22

C4_qt = [0.0;0.0];
