function Fs1 = MGspringforce(in1,in2,L0,K,in5,in6)
%MGSPRINGFORCE
%    FS1 = MGSPRINGFORCE(IN1,IN2,L0,K,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:23

com11 = in5(1,:);
com12 = in5(2,:);
ps11 = in1(1,:);
ps12 = in1(2,:);
ps21 = in2(1,:);
ps22 = in2(2,:);
theta1 = in6(3,:);
x1 = in6(1,:);
y1 = in6(2,:);
t3 = cos(theta1);
t4 = com12-ps22;
t5 = sin(theta1);
t6 = com11-ps21;
t8 = t3.*t6;
t9 = t4.*t5;
t2 = ps11+t8-t9-x1;
t11 = t3.*t4;
t12 = t5.*t6;
t7 = ps12+t11+t12-y1;
t10 = t2.^2;
t13 = t7.^2;
t14 = t10+t13;
t15 = sqrt(t14);
t16 = L0-t15;
t17 = 1.0./sqrt(t14);
Fs1 = [K.*t16.*t17.*(ps11.*2.0-x1.*2.0+t3.*t6.*2.0-t4.*t5.*2.0).*(-1.0./2.0);K.*t16.*t17.*(ps12.*2.0-y1.*2.0+t3.*t4.*2.0+t5.*t6.*2.0).*(-1.0./2.0);K.*t16.*t17.*(t2.*(t11+t12).*2.0-t7.*(t8-t9).*2.0).*(-1.0./2.0)];
