function C2_qq = MMH_qq(in1,in2,in3,in4,in5)
%MMH_QQ
%    C2_QQ = MMH_QQ(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:20

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in2(1,:);
com12 = in2(2,:);
com21 = in3(1,:);
com22 = in3(2,:);
theta1 = in4(3,:);
theta2 = in4(6,:);
thetad1 = in5(3,:);
thetad2 = in5(6,:);
t2 = thetad1.^2;
t3 = cos(theta1);
t4 = H12-com12;
t5 = sin(theta1);
t6 = H11-com11;
t7 = thetad2.^2;
t8 = cos(theta2);
t9 = H12-com22;
t10 = sin(theta2);
t11 = H11-com21;
C2_qq = [-t2.*(t3.*t6-t4.*t5)+t7.*(t8.*t11-t9.*t10);-t2.*(t3.*t4+t5.*t6)+t7.*(t8.*t9+t10.*t11)];
