function C2_q = MMH_q(in1,in2,in3,in4)
%MMH_Q
%    C2_Q = MMH_Q(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:20

H11 = in1(1,:);
H12 = in1(2,:);
com11 = in2(1,:);
com12 = in2(2,:);
com21 = in3(1,:);
com22 = in3(2,:);
theta1 = in4(3,:);
theta2 = in4(6,:);
t2 = cos(theta1);
t3 = H11-com11;
t4 = sin(theta1);
t5 = H12-com12;
t6 = cos(theta2);
t7 = H11-com21;
t8 = sin(theta2);
t9 = H12-com22;
C2_q = reshape([1.0,0.0,0.0,1.0,-t2.*t5-t3.*t4,t2.*t3-t4.*t5,-1.0,0.0,0.0,-1.0,t6.*t9+t7.*t8,-t6.*t7+t8.*t9],[2,6]);
