function Fs2 = MMspringforce(in1,in2,L0,K,in5,in6,in7)
%MMSPRINGFORCE
%    FS2 = MMSPRINGFORCE(IN1,IN2,L0,K,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    17-Oct-2016 18:51:24

com11 = in5(1,:);
com12 = in5(2,:);
com21 = in6(1,:);
com22 = in6(2,:);
ps11 = in1(1,:);
ps12 = in1(2,:);
ps21 = in2(1,:);
ps22 = in2(2,:);
theta1 = in7(3,:);
theta2 = in7(6,:);
x1 = in7(1,:);
x2 = in7(4,:);
y1 = in7(2,:);
y2 = in7(5,:);
t3 = cos(theta1);
t4 = com12-ps12;
t5 = cos(theta2);
t6 = com22-ps22;
t7 = sin(theta1);
t8 = com11-ps11;
t9 = sin(theta2);
t10 = com21-ps21;
t12 = t3.*t8;
t13 = t5.*t10;
t14 = t4.*t7;
t15 = t6.*t9;
t2 = -t12+t13+t14-t15+x1-x2;
t17 = t3.*t4;
t18 = t5.*t6;
t19 = t7.*t8;
t20 = t9.*t10;
t11 = -t17+t18-t19+t20+y1-y2;
t16 = t2.^2;
t21 = t11.^2;
t22 = t16+t21;
t23 = 1.0./sqrt(t22);
t24 = sqrt(t22);
t25 = L0-t24;
t26 = x1.*2.0;
t27 = t5.*t10.*2.0;
t28 = t4.*t7.*2.0;
t29 = t26+t27+t28-x2.*2.0-t3.*t8.*2.0-t6.*t9.*2.0;
t30 = K.*t23.*t25.*t29.*(1.0./2.0);
t31 = y1.*2.0;
t32 = t5.*t6.*2.0;
t33 = t9.*t10.*2.0;
t34 = t31+t32+t33-y2.*2.0-t3.*t4.*2.0-t7.*t8.*2.0;
t35 = K.*t23.*t25.*t34.*(1.0./2.0);
Fs2 = [t30;t35;K.*t23.*t25.*(t2.*(t17+t19).*2.0-t11.*(t12-t14).*2.0).*(1.0./2.0);-t30;-t35;K.*t23.*t25.*(t2.*(t18+t20).*2.0-t11.*(t13-t15).*2.0).*(-1.0./2.0)];
