/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGH.c
 *
 * Code generation for function 'MGH'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGH.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MGH(const real_T in1[5], const real_T in2[2], const real_T in3[3], real_T
         C1[2])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;

  /* MGH */
  /*     C1 = MGH(IN1,IN2,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:18 */
  t2 = muDoubleScalarCos(in3[2]);
  t3 = in1[1] - in2[1];
  t4 = muDoubleScalarSin(in3[2]);
  t5 = in1[0] - in2[0];
  C1[0] = ((-in1[0] + in3[0]) + t2 * t5) - t3 * t4;
  C1[1] = ((-in1[1] + in3[1]) + t2 * t3) + t4 * t5;
}

/* End of code generation (MGH.c) */
