/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGH_q.c
 *
 * Code generation for function 'MGH_q'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGH_q.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MGH_q(const real_T in1[5], const real_T in2[2], const real_T in3[3], real_T
           C1_q[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T x[6];
  int32_T k;

  /* MGH_Q */
  /*     C1_Q = MGH_Q(IN1,IN2,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:19 */
  t2 = muDoubleScalarCos(in3[2]);
  t3 = in1[0] - in2[0];
  t4 = muDoubleScalarSin(in3[2]);
  t5 = in1[1] - in2[1];
  x[0] = 1.0;
  x[1] = 0.0;
  x[2] = 0.0;
  x[3] = 1.0;
  x[4] = -t2 * t5 - t3 * t4;
  x[5] = t2 * t3 - t4 * t5;
  for (k = 0; k < 6; k++) {
    C1_q[k] = x[k];
  }
}

/* End of code generation (MGH_q.c) */
