/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGH_qq.c
 *
 * Code generation for function 'MGH_qq'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGH_qq.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MGH_qq(const real_T in1[5], const real_T in2[2], const real_T in3[3], const
            real_T in4[3], real_T C1_qq[2])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;

  /* MGH_QQ */
  /*     C1_QQ = MGH_QQ(IN1,IN2,IN3,IN4) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:19 */
  t2 = in4[2] * in4[2];
  t3 = muDoubleScalarCos(in3[2]);
  t4 = in1[1] - in2[1];
  t5 = muDoubleScalarSin(in3[2]);
  t6 = in1[0] - in2[0];
  C1_qq[0] = -t2 * (t3 * t6 - t4 * t5);
  C1_qq[1] = -t2 * (t3 * t4 + t5 * t6);
}

/* End of code generation (MGH_qq.c) */
