/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGP_qq.c
 *
 * Code generation for function 'MGP_qq'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGP_qq.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
real_T MGP_qq(const real_T in1[2], real_T alpha, const real_T in3[2], const
              real_T in4[3], const real_T in5[3])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;

  /* MGP_QQ */
  /*     C3_QQ = MGP_QQ(IN1,ALPHA,IN3,IN4,IN5) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:21 */
  t2 = muDoubleScalarCos(in4[2]);
  t3 = in1[0] - in3[0];
  t4 = muDoubleScalarSin(in4[2]);
  t5 = in1[1] - in3[1];
  return in5[2] * in5[2] * (muDoubleScalarCos(alpha) * (t2 * t5 + t3 * t4) -
    muDoubleScalarSin(alpha) * (t2 * t3 - t4 * t5));
}

/* End of code generation (MGP_qq.c) */
