/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGP_q.c
 *
 * Code generation for function 'MGP_q'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGP_q.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MGP_q(const real_T in1[2], real_T alpha, const real_T in3[2], const real_T
           in4[3], real_T C3_q[3])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;

  /* MGP_Q */
  /*     C3_Q = MGP_Q(IN1,ALPHA,IN3,IN4) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:21 */
  t2 = muDoubleScalarCos(alpha);
  t3 = muDoubleScalarSin(alpha);
  t4 = muDoubleScalarCos(in4[2]);
  t5 = in1[1] - in3[1];
  t6 = muDoubleScalarSin(in4[2]);
  t7 = in1[0] - in3[0];
  C3_q[0] = t3;
  C3_q[1] = -t2;
  C3_q[2] = -t2 * (t4 * t7 - t5 * t6) - t3 * (t4 * t5 + t6 * t7);
}

/* End of code generation (MGP_q.c) */
