/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGPm_q.c
 *
 * Code generation for function 'MGPm_q'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGPm_q.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MGPm_q(const real_T in1[2], real_T alpha, const real_T in5[2], const real_T
            in7[3], real_T C4_q[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T x[6];
  int32_T k;

  /* MGPM_Q */
  /*     C4_Q = MGPM_Q(IN1,ALPHA,A,W,IN5,T,IN7) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:22 */
  t2 = muDoubleScalarCos(alpha);
  t3 = muDoubleScalarSin(alpha);
  t4 = muDoubleScalarCos(in7[2]);
  t5 = in1[1] - in5[1];
  t6 = muDoubleScalarSin(in7[2]);
  t7 = in1[0] - in5[0];
  t8 = t4 * t7;
  t9 = t4 * t5;
  t10 = t6 * t7;
  x[0] = t3;
  x[1] = 1.0;
  x[2] = -t2;
  x[3] = 1.0;
  x[4] = -t3 * (t9 + t10) - t2 * (t8 - t5 * t6);
  x[5] = ((t8 - t9) - t10) - t5 * t6;
  for (k = 0; k < 6; k++) {
    C4_q[k] = x[k];
  }
}

/* End of code generation (MGPm_q.c) */
