/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGPm_qq.c
 *
 * Code generation for function 'MGPm_qq'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGPm_qq.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MGPm_qq(const real_T in1[2], real_T alpha, const real_T in5[2], const
             real_T in7[3], const real_T in8[3], real_T C4_qq[2])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;

  /* MGPM_QQ */
  /*     C4_QQ = MGPM_QQ(IN1,ALPHA,A,W,IN5,T,IN7,IN8) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:22 */
  t2 = muDoubleScalarCos(in7[2]);
  t3 = in1[0] - in5[0];
  t4 = muDoubleScalarSin(in7[2]);
  t5 = in1[1] - in5[1];
  t6 = in8[2] * in8[2];
  t7 = t2 * t3;
  t8 = t2 * t5;
  t9 = t3 * t4;
  C4_qq[0] = -t6 * (muDoubleScalarSin(alpha) * (t7 - t4 * t5) -
                    muDoubleScalarCos(alpha) * (t8 + t9));
  C4_qq[1] = -t6 * (((t7 + t8) + t9) - t4 * t5);
}

/* End of code generation (MGPm_qq.c) */
