/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGPm.c
 *
 * Code generation for function 'MGPm'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGPm.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MGPm(const real_T in1[2], real_T alpha, real_T a, real_T w, const real_T
          in5[2], real_T t, const real_T in7[3], real_T C4[2])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;

  /* MGPM */
  /*     C4 = MGPM(IN1,ALPHA,A,W,IN5,T,IN7) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:21 */
  t2 = muDoubleScalarCos(in7[2]);
  t3 = in1[1] - in5[1];
  t4 = muDoubleScalarSin(in7[2]);
  t5 = in1[0] - in5[0];
  t6 = t2 * t3;
  t7 = t4 * t5;
  t8 = t3 * t4;
  C4[0] = -muDoubleScalarSin(alpha) * (((in1[0] + t8) - in7[0]) - t2 * t5) -
    muDoubleScalarCos(alpha) * (((-in1[1] + t6) + t7) + in7[1]);
  C4[1] = (((((((-in1[0] - in1[1]) + t6) + t7) - t8) + in7[0]) + in7[1]) + t2 *
           t5) - a * muDoubleScalarSin(t * w);
}

/* End of code generation (MGPm.c) */
