/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MGspringforce.c
 *
 * Code generation for function 'MGspringforce'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGspringforce.h"
#include "error1.h"
#include "simulateDNA_data.h"
#include "blas.h"
#include "lapacke.h"

/* Variable Definitions */
static emlrtRSInfo yg_emlrtRSI = { 27, "MGspringforce",
  "C:\\Users\\Reinier\\Box Sync\\Reinier PhD\\3_Matlab\\Mechanical_engine\\deriveTerms\\MGspringforce.m"
};

static emlrtRSInfo ah_emlrtRSI = { 28, "MGspringforce",
  "C:\\Users\\Reinier\\Box Sync\\Reinier PhD\\3_Matlab\\Mechanical_engine\\deriveTerms\\MGspringforce.m"
};

static emlrtRSInfo bh_emlrtRSI = { 30, "MGspringforce",
  "C:\\Users\\Reinier\\Box Sync\\Reinier PhD\\3_Matlab\\Mechanical_engine\\deriveTerms\\MGspringforce.m"
};

static emlrtRSInfo ch_emlrtRSI = { 32, "MGspringforce",
  "C:\\Users\\Reinier\\Box Sync\\Reinier PhD\\3_Matlab\\Mechanical_engine\\deriveTerms\\MGspringforce.m"
};

/* Function Definitions */
void MGspringforce(const emlrtStack *sp, const real_T in1[2], const real_T in2[2],
                   real_T L0, real_T K, const real_T in5[2], const real_T in6[3],
                   real_T Fs1[3])
{
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t8;
  real_T t9;
  real_T t2;
  real_T t11;
  real_T t12;
  real_T t7;
  real_T t14;
  real_T t16;
  real_T t17;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MGSPRINGFORCE */
  /*     FS1 = MGSPRINGFORCE(IN1,IN2,L0,K,IN5,IN6) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:23 */
  t3 = muDoubleScalarCos(in6[2]);
  t4 = in5[1] - in2[1];
  t5 = muDoubleScalarSin(in6[2]);
  t6 = in5[0] - in2[0];
  t8 = t3 * t6;
  t9 = t4 * t5;
  t2 = ((in1[0] + t8) - t9) - in6[0];
  t11 = t3 * t4;
  t12 = t5 * t6;
  t7 = ((in1[1] + t11) + t12) - in6[1];
  st.site = &yg_emlrtRSI;
  st.site = &ah_emlrtRSI;
  t14 = t2 * t2 + t7 * t7;
  st.site = &bh_emlrtRSI;
  if (t14 < 0.0) {
    b_st.site = &gf_emlrtRSI;
    e_error(&b_st);
  }

  t16 = L0 - muDoubleScalarSqrt(t14);
  st.site = &ch_emlrtRSI;
  t17 = 1.0 / muDoubleScalarSqrt(t14);
  Fs1[0] = K * t16 * t17 * (((in1[0] * 2.0 - in6[0] * 2.0) + t3 * t6 * 2.0) - t4
    * t5 * 2.0) * -0.5;
  Fs1[1] = K * t16 * t17 * (((in1[1] * 2.0 - in6[1] * 2.0) + t3 * t4 * 2.0) + t5
    * t6 * 2.0) * -0.5;
  Fs1[2] = K * t16 * t17 * (t2 * (t11 + t12) * 2.0 - t7 * (t8 - t9) * 2.0) *
    -0.5;
}

/* End of code generation (MGspringforce.c) */
