/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MMH.c
 *
 * Code generation for function 'MMH'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMH.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MMH(const real_T in1[5], const real_T in2[2], const real_T in3[2], const
         real_T in4[6], real_T C2[2])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;

  /* MMH */
  /*     C2 = MMH(IN1,IN2,IN3,IN4) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:20 */
  t2 = muDoubleScalarCos(in4[2]);
  t3 = in1[1] - in2[1];
  t4 = muDoubleScalarCos(in4[5]);
  t5 = in1[1] - in3[1];
  t6 = muDoubleScalarSin(in4[2]);
  t7 = in1[0] - in2[0];
  t8 = muDoubleScalarSin(in4[5]);
  t9 = in1[0] - in3[0];
  C2[0] = ((((in4[0] - in4[3]) + t2 * t7) - t3 * t6) - t4 * t9) + t5 * t8;
  C2[1] = ((((in4[1] - in4[4]) + t2 * t3) - t4 * t5) + t6 * t7) - t8 * t9;
}

/* End of code generation (MMH.c) */
