/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MMH_q.c
 *
 * Code generation for function 'MMH_q'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMH_q.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MMH_q(const real_T in1[5], const real_T in2[2], const real_T in3[2], const
           real_T in4[6], real_T C2_q[12])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T x[12];

  /* MMH_Q */
  /*     C2_Q = MMH_Q(IN1,IN2,IN3,IN4) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:20 */
  t2 = muDoubleScalarCos(in4[2]);
  t3 = in1[0] - in2[0];
  t4 = muDoubleScalarSin(in4[2]);
  t5 = in1[1] - in2[1];
  t6 = muDoubleScalarCos(in4[5]);
  t7 = in1[0] - in3[0];
  t8 = muDoubleScalarSin(in4[5]);
  t9 = in1[1] - in3[1];
  x[0] = 1.0;
  x[1] = 0.0;
  x[2] = 0.0;
  x[3] = 1.0;
  x[4] = -t2 * t5 - t3 * t4;
  x[5] = t2 * t3 - t4 * t5;
  x[6] = -1.0;
  x[7] = 0.0;
  x[8] = 0.0;
  x[9] = -1.0;
  x[10] = t6 * t9 + t7 * t8;
  x[11] = -t6 * t7 + t8 * t9;
  memcpy(&C2_q[0], &x[0], 12U * sizeof(real_T));
}

/* End of code generation (MMH_q.c) */
