/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MMH_qq.c
 *
 * Code generation for function 'MMH_qq'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMH_qq.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MMH_qq(const real_T in1[5], const real_T in2[2], const real_T in3[2], const
            real_T in4[6], const real_T in5[6], real_T C2_qq[2])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;

  /* MMH_QQ */
  /*     C2_QQ = MMH_QQ(IN1,IN2,IN3,IN4,IN5) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:20 */
  t2 = in5[2] * in5[2];
  t3 = muDoubleScalarCos(in4[2]);
  t4 = in1[1] - in2[1];
  t5 = muDoubleScalarSin(in4[2]);
  t6 = in1[0] - in2[0];
  t7 = in5[5] * in5[5];
  t8 = muDoubleScalarCos(in4[5]);
  t9 = in1[1] - in3[1];
  t10 = muDoubleScalarSin(in4[5]);
  t11 = in1[0] - in3[0];
  C2_qq[0] = -t2 * (t3 * t6 - t4 * t5) + t7 * (t8 * t11 - t9 * t10);
  C2_qq[1] = -t2 * (t3 * t4 + t5 * t6) + t7 * (t8 * t9 + t10 * t11);
}

/* End of code generation (MMH_qq.c) */
