/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * MMtorsion.c
 *
 * Code generation for function 'MMtorsion'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMtorsion.h"
#include "blas.h"
#include "lapacke.h"

/* Function Definitions */
void MMtorsion(real_T K, real_T theta0, const real_T in3[6], real_T Ft2[6])
{
  real_T t4;

  /* MMTORSION */
  /*     FT2 = MMTORSION(K,THETA0,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     17-Oct-2016 18:51:25 */
  t4 = (theta0 * 2.0 + in3[2] * 2.0) - in3[5] * 2.0;
  Ft2[0] = 0.0;
  Ft2[1] = 0.0;
  Ft2[2] = K * t4 * -0.5;
  Ft2[3] = 0.0;
  Ft2[4] = 0.0;
  Ft2[5] = K * t4 * 0.5;
}

/* End of code generation (MMtorsion.c) */
