function Dq = getDq(phi2,phi3)
%GETDQ
%    DQ = GETDQ(PHI2,PHI3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-May-2017 09:43:30

t2 = sqrt(1.3e1);
t3 = sqrt(1.0e1);
Dq = reshape([-t2.*sin(phi2),t2.*cos(phi2),-t3.*sin(phi3),t3.*cos(phi3)],[2,2]);
