function dFdQ = getdFdQ(phi1,phi2,phi3)
%GETDFDQ
%    DFDQ = GETDFDQ(PHI1,PHI2,PHI3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    04-May-2017 16:33:01

t2 = sqrt(2.0);
t3 = sqrt(1.7e1);
dFdQ = reshape([-1.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,-t2.*sin(phi1),t2.*cos(phi1),0.0,0.0,0.0,0.0,0.0,0.0,-t3.*sin(phi2),t3.*cos(phi2),0.0,0.0,0.0,0.0,0.0,0.0,sin(phi3).*-2.0,cos(phi3).*2.0],[6,7]);
