function D = getD(phi1,phi2,phi3)
%GETD
%    D = GETD(PHI1,PHI2,PHI3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    04-May-2017 09:09:17

t2 = sqrt(5.0);
t3 = sqrt(1.0e1);
D = [cos(phi2).*2.0+t3.*cos(phi1)+t2.*cos(phi3)-4.0;sin(phi2).*2.0+t3.*sin(phi1)+t2.*sin(phi3)-1.0];
