function F = getF(phi1,phi2,phi3,x1,x2,y1,y2)
%GETF
%    F = GETF(PHI1,PHI2,PHI3,X1,X2,Y1,Y2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    04-May-2017 16:33:00

t2 = sqrt(2.0);
t3 = sqrt(1.7e1);
F = [-x1+t2.*cos(phi1)+1.0;-y1+t2.*sin(phi1);x1-x2+t3.*cos(phi2);y1-y2+t3.*sin(phi2);x2+cos(phi3).*2.0-4.0;y2+sin(phi3).*2.0];
