function F = getF(in1)
%GETF
%    F = GETF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Jun-2017 10:13:00

phi2 = in1(:,1);
phi3 = in1(:,2);
phi4 = in1(:,3);
phi5 = in1(:,4);
phi7 = in1(:,6);
phi8 = in1(:,7);
phi9 = in1(:,8);
phi10 = in1(:,9);
phi11 = in1(:,10);
phi12 = in1(:,11);
phi13 = in1(:,12);
phi14 = in1(:,13);
phi15 = in1(:,14);
phi16 = in1(:,15);
phi17 = in1(:,16);
phi18 = in1(:,17);
phi19 = in1(:,18);
phi20 = in1(:,19);
x3 = in1(:,20);
x4 = in1(:,21);
x5 = in1(:,22);
x6 = in1(:,23);
x7 = in1(:,24);
x8 = in1(:,25);
x9 = in1(:,26);
x10 = in1(:,27);
x11 = in1(:,28);
x12 = in1(:,29);
y3 = in1(:,30);
y4 = in1(:,31);
y5 = in1(:,32);
y6 = in1(:,33);
y7 = in1(:,34);
y8 = in1(:,35);
y9 = in1(:,36);
y10 = in1(:,37);
y11 = in1(:,38);
y12 = in1(:,39);
t2 = sqrt(5.0);
t3 = sqrt(8.5e1);
t4 = sqrt(2.0);
F = [x3-x7+sqrt(2.9e1);y3-y7;-x3+cos(phi2);-y3+sin(phi2);-x4+t2.*cos(phi3)+4.0;-y4+t2.*sin(phi3);x8-x9+t3.*cos(phi4).*(1.0./2.0);y8-y9+t3.*sin(phi4).*(1.0./2.0);-x5+cos(phi5).*(5.0./2.0)+4.0;-y5+sin(phi5).*(5.0./2.0);x11-x12;y11-y12;-x6+cos(phi7).*(5.0./2.0)+4.0;-y6+sin(phi7).*(5.0./2.0);x4-x6+cos(phi8).*(5.0./2.0);y4-y6+sin(phi8).*(5.0./2.0);-x7+t2.*cos(phi9).*2.0;-y7+t2.*sin(phi9).*2.0;-x7+t2.*cos(phi10).*2.0+4.0;-y7+t2.*sin(phi10).*2.0;-x8+cos(phi11).*(5.0./2.0)+4.0;-y8+sin(phi11).*(5.0./2.0);x4-x8+cos(phi12).*(5.0./2.0);y4-y8+sin(phi12).*(5.0./2.0);x3-x9+t4.*cos(phi13).*(5.0./2.0);y3-y9+t4.*sin(phi13).*(5.0./2.0);x4-x9+t4.*cos(phi14).*(5.0./2.0);y4-y9+t4.*sin(phi14).*(5.0./2.0);-x10+t2.*cos(phi15).*(5.0./4.0)+4.0;-y10+t2.*sin(phi15).*(5.0./4.0);x5-x10+t2.*cos(phi16).*(5.0./4.0);y5-y10+t2.*sin(phi16).*(5.0./4.0);x4-x11+t2.*cos(phi17).*(5.0./4.0);y4-y11+t2.*sin(phi17).*(5.0./4.0);x6-x11+t2.*cos(phi18).*(5.0./4.0);y6-y11+t2.*sin(phi18).*(5.0./4.0);x4-x12+t2.*cos(phi19).*(5.0./4.0);y4-y12+t2.*sin(phi19).*(5.0./4.0);x5-x12+t2.*cos(phi20).*(5.0./4.0);y5-y12+t2.*sin(phi20).*(5.0./4.0)];
