function F = getF(in1)
%GETF
%    F = GETF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    15-May-2017 15:49:53

phi2 = in1(:,1);
phi3 = in1(:,2);
phi4 = in1(:,3);
phi5 = in1(:,4);
phi6 = in1(:,5);
x3 = in1(:,6);
x4 = in1(:,7);
x5 = in1(:,8);
y3 = in1(:,9);
y4 = in1(:,10);
y5 = in1(:,11);
t2 = sqrt(1.0e1);
t3 = sqrt(5.0);
t4 = sqrt(8.5e1);
F = [0.0;0.0;-x3+t2.*cos(phi2);-y3+t2.*sin(phi2);-x4+t3.*cos(phi3)+2.0;-y4+t3.*sin(phi3);-x5+t4.*cos(phi4).*(1.0./2.0)+2.0;-y5+t4.*sin(phi4).*(1.0./2.0);x3-x5+cos(phi5).*(5.0./2.0);y3-y5+sin(phi5).*(5.0./2.0);x4-x5+cos(phi6).*(5.0./2.0);y4-y5+sin(phi6).*(5.0./2.0)];
