/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGH.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGH.h"

/* Function Definitions */

/*
 * MGH
 *     C1 = MGH(IN1,IN2,IN3)
 * Arguments    : const double in1[5]
 *                const double in2[2]
 *                const double in3[3]
 *                double C1[2]
 * Return Type  : void
 */
void MGH(const double in1[5], const double in2[2], const double in3[3], double
         C1[2])
{
  double t2;
  double t3;
  double t4;
  double t5;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:27 */
  t2 = cos(in3[2]);
  t3 = in1[1] - in2[1];
  t4 = sin(in3[2]);
  t5 = in1[0] - in2[0];
  C1[0] = ((-in1[0] + in3[0]) + t2 * t5) - t3 * t4;
  C1[1] = ((-in1[1] + in3[1]) + t2 * t3) + t4 * t5;
}

/*
 * File trailer for MGH.c
 *
 * [EOF]
 */
