/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGH_q.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGH_q.h"

/* Function Definitions */

/*
 * MGH_Q
 *     C1_Q = MGH_Q(IN1,IN2,IN3)
 * Arguments    : const double in1[5]
 *                const double in2[2]
 *                const double in3[3]
 *                double C1_q[6]
 * Return Type  : void
 */
void MGH_q(const double in1[5], const double in2[2], const double in3[3], double
           C1_q[6])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double x[6];
  int k;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:27 */
  t2 = cos(in3[2]);
  t3 = in1[0] - in2[0];
  t4 = sin(in3[2]);
  t5 = in1[1] - in2[1];
  x[0] = 1.0;
  x[1] = 0.0;
  x[2] = 0.0;
  x[3] = 1.0;
  x[4] = -t2 * t5 - t3 * t4;
  x[5] = t2 * t3 - t4 * t5;
  for (k = 0; k < 6; k++) {
    C1_q[k] = x[k];
  }
}

/*
 * File trailer for MGH_q.c
 *
 * [EOF]
 */
