/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGH_qq.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGH_qq.h"

/* Function Definitions */

/*
 * MGH_QQ
 *     C1_QQ = MGH_QQ(IN1,IN2,IN3,IN4)
 * Arguments    : const double in1[5]
 *                const double in2[2]
 *                const double in3[3]
 *                const double in4[3]
 *                double C1_qq[2]
 * Return Type  : void
 */
void MGH_qq(const double in1[5], const double in2[2], const double in3[3], const
            double in4[3], double C1_qq[2])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:28 */
  t2 = in4[2] * in4[2];
  t3 = cos(in3[2]);
  t4 = in1[1] - in2[1];
  t5 = sin(in3[2]);
  t6 = in1[0] - in2[0];
  C1_qq[0] = -t2 * (t3 * t6 - t4 * t5);
  C1_qq[1] = -t2 * (t3 * t4 + t5 * t6);
}

/*
 * File trailer for MGH_qq.c
 *
 * [EOF]
 */
