/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGP.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGP.h"

/* Function Definitions */

/*
 * MGP
 *     C3 = MGP(IN1,ALPHA,IN3,IN4)
 * Arguments    : const double in1[2]
 *                double alpha
 *                const double in3[2]
 *                const double in4[3]
 * Return Type  : double
 */
double MGP(const double in1[2], double alpha, const double in3[2], const double
           in4[3])
{
  double t2;
  double t3;
  double t4;
  double t5;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:29 */
  t2 = cos(in4[2]);
  t3 = in1[1] - in3[1];
  t4 = sin(in4[2]);
  t5 = in1[0] - in3[0];
  return -cos(alpha) * (((-in1[1] + in4[1]) + t2 * t3) + t4 * t5) - sin(alpha) *
    (((in1[0] - in4[0]) - t2 * t5) + t3 * t4);
}

/*
 * File trailer for MGP.c
 *
 * [EOF]
 */
