/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGP_q.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGP_q.h"

/* Function Definitions */

/*
 * MGP_Q
 *     C3_Q = MGP_Q(IN1,ALPHA,IN3,IN4)
 * Arguments    : const double in1[2]
 *                double alpha
 *                const double in3[2]
 *                const double in4[3]
 *                double C3_q[3]
 * Return Type  : void
 */
void MGP_q(const double in1[2], double alpha, const double in3[2], const double
           in4[3], double C3_q[3])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:29 */
  t2 = cos(alpha);
  t3 = sin(alpha);
  t4 = cos(in4[2]);
  t5 = in1[1] - in3[1];
  t6 = sin(in4[2]);
  t7 = in1[0] - in3[0];
  C3_q[0] = t3;
  C3_q[1] = -t2;
  C3_q[2] = -t2 * (t4 * t7 - t5 * t6) - t3 * (t4 * t5 + t6 * t7);
}

/*
 * File trailer for MGP_q.c
 *
 * [EOF]
 */
