/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGPm.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGPm.h"

/* Function Definitions */

/*
 * MGPM
 *     C4 = MGPM(IN1,ALPHA,A,W,IN5,T,IN7)
 * Arguments    : const double in1[2]
 *                double alpha
 *                double a
 *                double w
 *                const double in5[2]
 *                double t
 *                const double in7[3]
 *                double C4[2]
 * Return Type  : void
 */
void MGPm(const double in1[2], double alpha, double a, double w, const double
          in5[2], double t, const double in7[3], double C4[2])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:29 */
  t2 = cos(in7[2]);
  t3 = in1[1] - in5[1];
  t4 = sin(in7[2]);
  t5 = in1[0] - in5[0];
  t6 = t3 * t4;
  C4[0] = -cos(alpha) * (((-in1[1] + in7[1]) + t2 * t3) + t4 * t5) - sin(alpha) *
    (((in1[0] + t6) - in7[0]) - t2 * t5);
  C4[1] = (((-in1[0] - t6) + in7[0]) + t2 * t5) + a * sin(t * w);
}

/*
 * File trailer for MGPm.c
 *
 * [EOF]
 */
