/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGPm_qq.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGPm_qq.h"

/* Function Definitions */

/*
 * MGPM_QQ
 *     C4_QQ = MGPM_QQ(IN1,ALPHA,A,W,IN5,T,IN7,IN8)
 * Arguments    : const double in1[2]
 *                double alpha
 *                const double in5[2]
 *                const double in7[3]
 *                const double in8[3]
 *                double C4_qq[2]
 * Return Type  : void
 */
void MGPm_qq(const double in1[2], double alpha, const double in5[2], const
             double in7[3], const double in8[3], double C4_qq[2])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t8;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:30 */
  t2 = cos(in7[2]);
  t3 = in1[0] - in5[0];
  t4 = sin(in7[2]);
  t5 = in1[1] - in5[1];
  t6 = in8[2] * in8[2];
  t8 = t2 * t3 - t4 * t5;
  C4_qq[0] = t6 * (cos(alpha) * (t2 * t5 + t3 * t4) - t8 * sin(alpha));
  C4_qq[1] = -t6 * t8;
}

/*
 * File trailer for MGPm_qq.c
 *
 * [EOF]
 */
