/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MGPm_q.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MGPm_q.h"

/* Function Definitions */

/*
 * MGPM_Q
 *     C4_Q = MGPM_Q(IN1,ALPHA,A,W,IN5,T,IN7)
 * Arguments    : const double in1[2]
 *                double alpha
 *                const double in5[2]
 *                const double in7[3]
 *                double C4_q[6]
 * Return Type  : void
 */
void MGPm_q(const double in1[2], double alpha, const double in5[2], const double
            in7[3], double C4_q[6])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double x[6];
  int k;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:29 */
  t2 = cos(alpha);
  t3 = sin(alpha);
  t4 = cos(in7[2]);
  t5 = in1[1] - in5[1];
  t6 = sin(in7[2]);
  t7 = in1[0] - in5[0];
  t8 = t4 * t5;
  t9 = t6 * t7;
  x[0] = t3;
  x[1] = 1.0;
  x[2] = -t2;
  x[3] = 0.0;
  x[4] = -t3 * (t8 + t9) - t2 * (t4 * t7 - t5 * t6);
  x[5] = -t8 - t9;
  for (k = 0; k < 6; k++) {
    C4_q[k] = x[k];
  }
}

/*
 * File trailer for MGPm_q.c
 *
 * [EOF]
 */
