/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MMH.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMH.h"

/* Function Definitions */

/*
 * MMH
 *     C2 = MMH(IN1,IN2,IN3,IN4)
 * Arguments    : const double in1[5]
 *                const double in2[2]
 *                const double in3[2]
 *                const double in4[6]
 *                double C2[2]
 * Return Type  : void
 */
void MMH(const double in1[5], const double in2[2], const double in3[2], const
         double in4[6], double C2[2])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:28 */
  t2 = cos(in4[2]);
  t3 = in1[1] - in2[1];
  t4 = cos(in4[5]);
  t5 = in1[1] - in3[1];
  t6 = sin(in4[2]);
  t7 = in1[0] - in2[0];
  t8 = sin(in4[5]);
  t9 = in1[0] - in3[0];
  C2[0] = ((((in4[0] - in4[3]) + t2 * t7) - t3 * t6) - t4 * t9) + t5 * t8;
  C2[1] = ((((in4[1] - in4[4]) + t2 * t3) - t4 * t5) + t6 * t7) - t8 * t9;
}

/*
 * File trailer for MMH.c
 *
 * [EOF]
 */
