/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MMH_q.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMH_q.h"

/* Function Definitions */

/*
 * MMH_Q
 *     C2_Q = MMH_Q(IN1,IN2,IN3,IN4)
 * Arguments    : const double in1[5]
 *                const double in2[2]
 *                const double in3[2]
 *                const double in4[6]
 *                double C2_q[12]
 * Return Type  : void
 */
void MMH_q(const double in1[5], const double in2[2], const double in3[2], const
           double in4[6], double C2_q[12])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double x[12];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:28 */
  t2 = cos(in4[2]);
  t3 = in1[0] - in2[0];
  t4 = sin(in4[2]);
  t5 = in1[1] - in2[1];
  t6 = cos(in4[5]);
  t7 = in1[0] - in3[0];
  t8 = sin(in4[5]);
  t9 = in1[1] - in3[1];
  x[0] = 1.0;
  x[1] = 0.0;
  x[2] = 0.0;
  x[3] = 1.0;
  x[4] = -t2 * t5 - t3 * t4;
  x[5] = t2 * t3 - t4 * t5;
  x[6] = -1.0;
  x[7] = 0.0;
  x[8] = 0.0;
  x[9] = -1.0;
  x[10] = t6 * t9 + t7 * t8;
  x[11] = -t6 * t7 + t8 * t9;
  memcpy(&C2_q[0], &x[0], 12U * sizeof(double));
}

/*
 * File trailer for MMH_q.c
 *
 * [EOF]
 */
