/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MMH_qq.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMH_qq.h"

/* Function Definitions */

/*
 * MMH_QQ
 *     C2_QQ = MMH_QQ(IN1,IN2,IN3,IN4,IN5)
 * Arguments    : const double in1[5]
 *                const double in2[2]
 *                const double in3[2]
 *                const double in4[6]
 *                const double in5[6]
 *                double C2_qq[2]
 * Return Type  : void
 */
void MMH_qq(const double in1[5], const double in2[2], const double in3[2], const
            double in4[6], const double in5[6], double C2_qq[2])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double t10;
  double t11;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:28 */
  t2 = in5[2] * in5[2];
  t3 = cos(in4[2]);
  t4 = in1[1] - in2[1];
  t5 = sin(in4[2]);
  t6 = in1[0] - in2[0];
  t7 = in5[5] * in5[5];
  t8 = cos(in4[5]);
  t9 = in1[1] - in3[1];
  t10 = sin(in4[5]);
  t11 = in1[0] - in3[0];
  C2_qq[0] = -t2 * (t3 * t6 - t4 * t5) + t7 * (t8 * t11 - t9 * t10);
  C2_qq[1] = -t2 * (t3 * t4 + t5 * t6) + t7 * (t8 * t9 + t10 * t11);
}

/*
 * File trailer for MMH_qq.c
 *
 * [EOF]
 */
