/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: MMtorsion.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 17-Oct-2016 17:50:39
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "simulateDNA.h"
#include "MMtorsion.h"

/* Function Definitions */

/*
 * MMTORSION
 *     FT2 = MMTORSION(K,THETA0,IN3)
 * Arguments    : double K
 *                double theta0
 *                const double in3[6]
 *                double Ft2[6]
 * Return Type  : void
 */
void MMtorsion(double K, double theta0, const double in3[6], double Ft2[6])
{
  double t4;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     04-Jul-2016 16:03:32 */
  t4 = (theta0 * 2.0 + in3[2] * 2.0) - in3[5] * 2.0;
  Ft2[0] = 0.0;
  Ft2[1] = 0.0;
  Ft2[2] = K * t4 * -0.5;
  Ft2[3] = 0.0;
  Ft2[4] = 0.0;
  Ft2[5] = K * t4 * 0.5;
}

/*
 * File trailer for MMtorsion.c
 *
 * [EOF]
 */
